import 'animate.css'
import './globals.scss'
// add bootstrap css
import 'bootstrap/dist/css/bootstrap.css'
// add bs-icons
import 'bootstrap-icons/font/bootstrap-icons.css'
import { Fireworks } from '@/components/Fireworks'
import TopBar from '@/components/MainPage/TopBar/TopBar'

export const metadata = {
  title: "Lycoiref's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh">
      <body>
        <TopBar />
        <Fireworks />
        {children}
      </body>
    </html>
  )
}
