import './globals.css'

export const metadata = {
    title: "Lycoiref's Blog",
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="zh">
            <body>{children}</body>
        </html>
    )
}
